Feature/admin dashboard UI
TripPlus-003/TripPlus-admin pull request #11
Opened 2023-05-27 09:05 UTC by gn00678465

2023-05-27 17:33 UTC, happy9990929 requested changes

2023-05-27 17:33 UTC, happy9990929 commented on src/pages/admin/[id]/dashboard/index.tsx
> +        </h2>
想讓電腦版標題可限制行數，最多兩行
md:line-clamp-2

2023-05-27 17:33 UTC, happy9990929 commented on src/pages/admin/[id]/dashboard/index.tsx
> +            </Text>
文字大小
倒數、天 電腦版 18 px，手機 16 px
數字 電腦版 20 px，手機 18 px

2023-05-28 17:28 UTC, happy9990929 approved these changes
Good job

2023-05-29 01:32 UTC, yuhantaiwan approved these changes
great

2023-05-29 01:32 UTC, merged