feat: 團隊資料 api 串接
TripPlus-003/TripPlus-admin pull request #21
Opened 2023-06-25 17:19 UTC by yuhantaiwan

2023-06-26 12:19 UTC, gn00678465 approved these changes
Good job

2023-06-27 17:34 UTC, happy9990929 requested changes

2023-06-27 17:34 UTC, happy9990929 commented on src/pages/admin/[id]/team.tsx
> +        </Text>
與 label 統一文字大小

2023-06-30 02:42 UTC, happy9990929 approved these changes
Good job

2023-06-30 02:42 UTC, merged