feat: 後台登入頁面
TripPlus-003/TripPlus-admin pull request #4
Opened 2023-05-01 14:21 UTC by gn00678465

2023-05-03 13:33 UTC, yuhantaiwan requested changes

2023-05-03 13:33 UTC, yuhantaiwan commented on .env.production
> +BASE_API_URL=https://trip-plus-server-dev.zeabur.app
production 環境的 API_URL 應該會把 **-dev** 拿掉

2023-05-03 14:55 UTC, happy9990929 approved these changes

2023-05-06 12:32 UTC, yuhantaiwan approved these changes

2023-05-06 12:32 UTC, merged