feat: 專案列表
TripPlus-003/TripPlus-admin pull request #7
Opened 2023-05-08 12:39 UTC by gn00678465

1. 新增專案列表頁面

2023-05-16 14:24 UTC, happy9990929 requested changes

2023-05-16 14:24 UTC, happy9990929 commented on src/components/Table/index.tsx
> +                  </Th>
Th 文字可以再大一點，如 1rem
集資金額、actions 希望可以統一置左

2023-05-16 14:24 UTC, happy9990929 commented on src/pages/admin/projects/index.tsx
> +        );
募資按鈕顏色想改 bgColor={'primary.500'} color="white"

2023-05-16 14:24 UTC, happy9990929 commented on src/pages/admin/projects/index.tsx
> +            </InputGroup>
手機板 全部類型、全部狀態、搜尋 上下 可再多留一點間距

2023-05-19 11:25 UTC, happy9990929 approved these changes

2023-05-20 12:05 UTC, gn00678465 commented
1. 串接 API
2. 加入篩選功能
3. 加入 table loading 效果
4. 補完連結
5. 修正衝突

2023-05-20 17:31 UTC, happy9990929 requested changes

2023-05-20 17:31 UTC, happy9990929 commented on src/pages/admin/projects/index.tsx
> +    }),
專案名稱需有連結，點擊後進 Dashboard

2023-05-21 04:20 UTC, happy9990929 approved these changes

2023-05-23 02:35 UTC, yuhantaiwan approved these changes
great

2023-05-23 02:35 UTC, merged