feat: 新增專案
TripPlus-003/TripPlus-admin pull request #8
Opened 2023-05-16 05:22 UTC by gn00678465

2023-05-16 14:49 UTC, happy9990929 requested changes

2023-05-16 14:49 UTC, happy9990929 commented on src/pages/admin/project/index.tsx
> +      <div className="h-full min-h-screen bg-gray-100">
頁面上下可多留點間距，如 padding: 1.5rem 0;

2023-05-17 02:38 UTC, happy9990929 requested changes

2023-05-17 02:38 UTC, happy9990929 commented on src/pages/admin/project/index.tsx
> +
沒上傳圖片就提交時無法送出，可以加個需上傳圖片的提示

2023-05-17 06:40 UTC, gn00678465 commented
1. 頁面上下間距
2. 未選擇專案圖片的錯誤顯示
3. 專案結束時間早於專案開始時間會顯示錯誤
4. 調整表單結構

2023-05-17 13:46 UTC, happy9990929 approved these changes

2023-05-19 08:33 UTC, yuhantaiwan requested changes

2023-05-19 08:33 UTC, yuhantaiwan commented on src/pages/admin/project/index.tsx
> +                  <option value={1}>精選商品</option>
option value 應該是 1: 創新設計、2: 精選商品

2023-05-19 14:03 UTC, yuhantaiwan approved these changes

2023-05-19 14:03 UTC, merged