Feature/Dashboard 與專案資訊 layout 切版
TripPlus-003/TripPlus-admin pull request #9
Opened 2023-05-18 21:50 UTC by gn00678465

2023-05-21 16:30 UTC, yuhantaiwan approved these changes

2023-05-23 13:29 UTC, happy9990929 requested changes

2023-05-23 13:29 UTC, happy9990929 commented on src/config/theme/index.ts
>  };
顏色少設定 gray

2023-05-23 13:29 UTC, happy9990929 commented on src/components/AdminLayout/components/Sidebar/index.tsx
> +    >
電腦版應皆為同樣間距
因 sidebar md 就變 100% 了，此處 md 較為合適
px={{ base: 3, md: 5 }}
pt={{ base: 5, md: 20 }}
pb={{ base: 5, md: 10 }}

2023-05-23 13:29 UTC, happy9990929 commented on src/components/AdminLayout/components/Sidebar/components/SidebarButton/index.tsx
> +        {children}
icon 可再放大，
設計稿電腦版約 24px
手機板約 20px

2023-05-23 13:29 UTC, happy9990929 commented on src/components/AdminLayout/components/Sidebar/index.tsx
> +        >
選單可否置中顯示，平版解析度時會離太開

2023-05-23 13:29 UTC, happy9990929 commented on src/components/AdminLayout/components/Sidebar/index.tsx
> +          </Text>
文字為 #1A1A1A
在 IOS 看時外框會是方形，看看 outline 是否要改 border

2023-05-23 16:52 UTC, gn00678465 commented on src/components/AdminLayout/components/Sidebar/index.tsx
> +          </Text>
這個 component border 看不出來效果
改使用 ring 的方式

2023-05-24 12:11 UTC, happy9990929 approved these changes

2023-05-24 13:22 UTC, yuhantaiwan approved these changes
great

2023-05-24 13:22 UTC, merged